apiVersion: v1
kind: Service
metadata:
  name: kuber0demo-api
  labels:
    app: kuber0demo-api
spec:
  selector:
    app: kuber0demo-api
  ports:
    - protocol: TCP
      port: 3000 #service port
      targetPort: 3000 #container port
  type: NodePort #expose service to node
